name: pr-check

on:
  pull_request:
    branches:
      - main
      - 'releases/*'
      
  workflow_dispatch:

jobs:
    build:
      environment: Automation test
      runs-on: windows-latest
      steps:
      - name: Checkout from PR branch  
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: installing node_modules
        run: npm install 
       
      - name: Build GitHub Action
        run: npm run build
      
      - name: Run Unit and Functional Tests
        run: npm run test
